"use strict";
let imie = "Jan";
let nazwisko = "Kowalski";
let tekst = `moje imie to ${imie}, a nazwisko ${nazwisko}`;
console.log(`${imie}, ${nazwisko}, ${tekst}`);
let liczba1 = 5;
let liczba2 = 23.4;
let liczba3 = 5322100;
let liczba4 = 0xfff;
console.log(`${liczba1}, ${liczba2}, ${liczba3}, ${liczba4}`);
let costam;
costam = true;
let cokolwiek;
cokolwiek = 5;
cokolwiek = "hej";
console.log(`${typeof cokolwiek}`);
let wspolna;
wspolna = 22;
wspolna = "dsds";
wspolna = true;
console.log(`${typeof wspolna}`);
